spring.application.name=Shoppy
server.port=8080
app.base-url=${APP_BASE_URL:http://localhost:8080}

# DATABASE CONFIG
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shoppy_db?options=-c%20timezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CLOUDINARY CONFIG
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# MAIL CONFIG (BREVO SMTP)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

app.mail.from=${MAIL_FROM:noreply@shoppy.com}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# T?ng timeout cho môi tr??ng Cloud
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# SECURITY CONFIG
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

app.default-avatar-url=${DEFAULT_AVATAR_URL:https://res.cloudinary.com/dii10rze6/image/upload/v1790846872/shoppy_avatars/vzsefqbb6qlp0zqtx3yy.png}